# Generated by Django 2.2.16 on 2021-01-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_endpoint', '0015_providerendpoint_add_plus_in_caller'),
        ('pyfb_endpoint', '0004_auto_20181219_1402'),
    ]

    operations = [
    ]
