# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trusted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(db_index=True, default=b'', help_text='Source address is equal to source address of request', max_length=50)),
                ('proto', models.CharField(choices=[(b'any', b'any'), (b'udp', b'udp'), (b'tcp', b'tcp'), (b'tls', b'tls'), (b'sctp', b'sctp')], default=b'any', help_text='Transport protocol is either any or equal to transport protocol of request', max_length=4)),
                ('from_pattern', models.CharField(blank=True, help_text='Regular expression matches From URI of request.', max_length=64, null=True)),
                ('ruri_pattern', models.CharField(blank=True, help_text='Regular expression matches Request URI of request.', max_length=64, null=True)),
                ('tag', models.CharField(default=b'', help_text='Tag', max_length=64)),
                ('priority', models.IntegerField(default=0, help_text='Priority of rule')),
            ],
            options={
                'ordering': ('-pk',),
                'db_table': 'trusted',
            },
        ),
        migrations.CreateModel(
            name='UacReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_uuid', models.CharField(db_index=True, default=b'', help_text='Local unique id used to build and match contact addresses.', max_length=64)),
                ('l_username', models.CharField(default=b'', help_text='Local username', max_length=64)),
                ('l_domain', models.CharField(default=b'', help_text='Local domain', max_length=64)),
                ('r_username', models.CharField(default=b'', help_text='Remote username', max_length=64)),
                ('r_domain', models.CharField(default=b'', help_text='Remote domain', max_length=64)),
                ('realm', models.CharField(default=b'', help_text='realm', max_length=64)),
                ('auth_username', models.CharField(default=b'', help_text='Auth username', max_length=64)),
                ('auth_password', models.CharField(default=b'', help_text='Auth password', max_length=64)),
                ('auth_ha1', models.CharField(default=b'', help_text='Hashed (HA1) auth password', max_length=128)),
                ('auth_proxy', models.CharField(default=b'', help_text='Outbound proxy SIP address', max_length=128)),
                ('expires', models.IntegerField(default=0, help_text='Expiration time in seconds, 0 means disabled')),
                ('flags', models.IntegerField(default=0, help_text='Flags to control the behaviour')),
                ('reg_delay', models.IntegerField(default=0, help_text='initial registration delay')),
            ],
            options={
                'ordering': ('-pk',),
                'db_table': 'uacreg',
            },
        ),
    ]
