# Generated by Django 2.1.5 on 2019-01-30 18:04

from django.db import migrations
import django.utils.timezone
import migrate_sql.operations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_direction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='créé'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='mise à jour'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='créé'),
        ),
        migrations.AlterField(
            model_name='country',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='mise à jour'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='créé'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='mise à jour'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='créé'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='mise à jour'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='créé'),
        ),
        migrations.AlterField(
            model_name='region',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='mise à jour'),
        ),
        migrations.AlterField(
            model_name='type',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='créé'),
        ),
        migrations.AlterField(
            model_name='type',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='mise à jour'),
        ),
        migrate_sql.operations.CreateSQL(
            name='dialplan_view',
            sql='DROP VIEW IF EXISTS pyfb_direction CASCADE; CREATE OR REPLACE VIEW pyfb_direction AS SELECT row_number() OVER () AS id, * FROM (  SELECT  p.prefix,  p.destination_id,  d.name AS destination_name,  d.carrier_id,  ca.name AS carrier_name,  d.country_iso2_id,  d.type_id,  t.name AS type_name,  c.region_id,  r.name AS region_name FROM pyfb_direction_prefix p LEFT JOIN pyfb_direction_destination d  ON d.id = p.destination_id LEFT JOIN pyfb_direction_carrier ca  ON ca.id = d.carrier_id LEFT JOIN pyfb_direction_type t  ON t.id = d.type_id LEFT JOIN pyfb_direction_country c ON c.country_iso2 = d.country_iso2_id LEFT JOIN pyfb_direction_region r  ON r.id = c.region_id) v;',
            reverse_sql='DROP VIEW IF EXISTS dialplan CASCADE; ',
        ),
    ]
