# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-18 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencyfr', '0002_auto_20161118_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caau',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caau',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inseecitycode',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inseecitycode',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdau',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdau',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
