# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-09 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urgencyfr', '0003_auto_20161118_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caau',
            options={'ordering': ('caau_code', 'long_number'), 'verbose_name': "Centre d'accueil des appels d'urgence", 'verbose_name_plural': "Centres d'accueil des appels d'urgence"},
        ),
        migrations.RenameField(
            model_name='caau',
            old_name='caau_id',
            new_name='caau_code',
        ),
        migrations.RenameField(
            model_name='inseecitycode',
            old_name='date_end',
            new_name='new_date',
        ),
        migrations.RenameField(
            model_name='pdau',
            old_name='date_end',
            new_name='new_date',
        ),
        migrations.RemoveField(
            model_name='caau',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='caau',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='caau',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='inseecitycode',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='pdau',
            name='date_start',
        ),
        migrations.AddField(
            model_name='caau',
            name='new_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='new date'),
        ),
        migrations.AddField(
            model_name='caau',
            name='new_long_number',
            field=models.CharField(blank=True, default=b'', help_text=b'Format E.164 pr\xc3\xa9fix\xc3\xa9 avec +', max_length=16, verbose_name="Nouveau num\xe9ro court d'urgence"),
        ),
        migrations.AddField(
            model_name='pdau',
            name='new_caau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newcaau', to='urgencyfr.Caau', verbose_name='Nouveau CAAU'),
        ),
        migrations.AlterField(
            model_name='pdau',
            name='caau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caau', to='urgencyfr.Caau', verbose_name='CAAU'),
        ),
    ]
