# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencyfr', '0004_auto_20170109_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caau',
            name='new_long_number',
            field=models.CharField(blank=True, default=b'', help_text=b'Format E.164 pr\xc3\xa9fix\xc3\xa9 avec +', max_length=16, null=True, verbose_name="Nouveau num\xe9ro court d'urgence"),
        ),
        migrations.AlterField(
            model_name='inseecitycode',
            name='new_code',
            field=models.CharField(blank=True, default=b'', help_text='Pour les communes appartenant \xe0\n            un d\xe9partement dont le code commence par \xab 0 \xbb,\n            il est n\xe9cessaire de saisir aussi le code insee\n            sur 5 chiffres.', max_length=5, null=True, verbose_name='Nouveau Code INSEE'),
        ),
    ]
