# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0002_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='voipswitch',
            name='fstype',
            field=models.CharField(choices=[(b'FREESWITCH', 'FREESWITCH'), (b'KAMAILIO', 'KAMAILIO'), (b'WAVFREESWITCH', 'FREESWITCH FOR TECHNICAL VOICE MESSAGES')], default=b'FREESWITCH', help_text='Select the switch type (Kamailio, FreeSwitch)', max_length=10, verbose_name='Switch type'),
        ),
    ]
