# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0003_voipswitch_fstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='voipswitch',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
