# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0004_voipswitch_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='voipswitch',
            name='attrs',
            field=models.CharField(default=b'ClueCon', help_text='Attrs.', max_length=128, verbose_name='attrs'),
        ),
        migrations.AddField(
            model_name='voipswitch',
            name='description',
            field=models.CharField(default=b'', help_text='Description.', max_length=64, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='voipswitch',
            name='flags',
            field=models.PositiveIntegerField(default=b'0', help_text='Flags.', verbose_name='flags'),
        ),
        migrations.AddField(
            model_name='voipswitch',
            name='priority',
            field=models.PositiveIntegerField(default=b'0', help_text='Priority.', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='voipswitch',
            name='fstype',
            field=models.CharField(choices=[(10, 'FREESWITCH'), (0, 'KAMAILIO'), (1, 'FREESWITCH FOR TECHNICAL VOICE MESSAGES')], default=0, help_text='Select the switch type (Kamailio, FreeSwitch)', max_length=10, verbose_name='Switch type'),
        ),
    ]
