# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0005_auto_20161215_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voipswitch',
            name='fstype',
        ),
        migrations.AddField(
            model_name='voipswitch',
            name='setid',
            field=models.CharField(choices=[(10, 'FREESWITCH'), (0, 'KAMAILIO'), (1, 'FREESWITCH FOR TECHNICAL VOICE MESSAGES')], default=0, help_text='Select the switch type (Kamailio, FreeSwitch)', max_length=10, verbose_name='Switch type'),
        ),
    ]
