# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0006_auto_20161215_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voipswitch',
            name='setid',
            field=models.PositiveIntegerField(choices=[(10, 'FREESWITCH'), (0, 'KAMAILIO'), (1, 'FREESWITCH FOR TECHNICAL VOICE MESSAGES')], default=0, help_text='Select the switch type (Kamailio, FreeSwitch)', max_length=10, verbose_name='Switch type'),
        ),
    ]
