# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0009_auto_20161215_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voipswitch',
            name='setid',
            field=models.PositiveIntegerField(choices=[(b'10', 'FREESWITCH'), (b'0', 'KAMAILIO'), (b'1', 'FREESWITCH FOR TECHNICAL VOICE MESSAGES')], default=b'0', help_text='Select the switch type (Kamailio, FreeSwitch)', verbose_name='Switch type'),
        ),
    ]
