# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0010_auto_20161215_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voipswitch',
            name='description',
            field=models.CharField(blank=True, default=b' ', help_text='Description.', max_length=64, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='voipswitch',
            name='setid',
            field=models.IntegerField(choices=[(10, 'FREESWITCH'), (0, 'KAMAILIO'), (1, 'FREESWITCH FOR TECHNICAL VOICE MESSAGES')], default=0, help_text='Select the switch type (Kamailio, FreeSwitch)', verbose_name='Switch type'),
        ),
    ]
