# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0012_voipswitchprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='voipswitchprofile',
            name='direction',
            field=models.IntegerField(choices=[(1, 'IN'), (2, 'OUT')], default=1, help_text='Select the direction of calls for this profile', verbose_name='Call direction'),
        ),
    ]
