# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0014_auto_20161215_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voipswitch',
            name='attrs',
            field=models.CharField(blank=True, default=b' ', help_text='Attrs.', max_length=128, verbose_name='attrs'),
        ),
    ]
