# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 17:24
from __future__ import unicode_literals

from django.db import migrations
import migrate_sql.operations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0015_auto_20161215_1815'),
    ]

    operations = [
        migrate_sql.operations.CreateSQL(
            name=b'dispatcher_view',
            sql=b"DROP VIEW IF EXISTS dispatcher CASCADE; CREATE OR REPLACE VIEW dispatcher AS  SELECT row_number() OVER () AS id,  f.setid,  CONCAT('sip:', f.ip, ':', sp.sip_port) AS destination,  f.flags,  f.priority,  f.attrs,  f.description FROM fs_switch f LEFT JOIN fs_switch_profile fsp  ON fsp.fsswitch_id = f.id AND fsp.direction = 1 LEFT JOIN sip_profile sp  ON sp.enabled = TRUE AND sp.id = fsp.sipprofile_id WHERE f.setid=10 AND f.enabled=TRUE;",
            reverse_sql=b'DROP dispatcher',
        ),
    ]
