# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-20 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0020_auto_20161220_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='voipswitchprofile',
            name='outbound_proxy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outboundproxy', to='switch.VoipSwitch', verbose_name='Kamailio server'),
            preserve_default=False,
        ),
    ]
