# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccCdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, default=b'2000-01-01 00:00:00', help_text='Start date and time')),
                ('end_time', models.DateTimeField(default=b'2000-01-01 00:00:00', help_text='End date and time')),
                ('duration', models.DecimalField(decimal_places=3, default=0, help_text='Duration', max_digits=10)),
            ],
            options={
                'ordering': ('-pk',),
                'db_table': 'acc_cdrs',
            },
        ),
    ]
