# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdirectory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'db_table': 'subscriber',
                'managed': False,
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
