# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0002_domain'),
        ('customerdirectory', '0004_auto_20161116_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdirectory',
            name='domain',
            field=models.ForeignKey(default=1, help_text='A sip account must belong to a domain.\n        This domain must be used in SIP message', on_delete=django.db.models.deletion.CASCADE, to='switch.Domain', verbose_name=b'SIP domain'),
            preserve_default=False,
        ),
    ]
