# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerdirectory', '0005_customerdirectory_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdirectory',
            name='domain',
            field=models.ForeignKey(help_text='A sip account must belong to a domain.\n            This domain must be used in SIP message', on_delete=django.db.models.deletion.CASCADE, to='switch.Domain', verbose_name='SIP domain'),
        ),
    ]
