# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdirectory', '0006_auto_20161117_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdirectory',
            name='force_caller_id',
            field=models.BooleanField(default=False, verbose_name='Force callerID'),
        ),
        migrations.AddField(
            model_name='customerdirectory',
            name='insee_code',
            field=models.PositiveIntegerField(blank=True, help_text='Postal code, INSEE code ... for routing\n          urgency number to the right urgency call center.', null=True, verbose_name='Special code for routing urgency numbers'),
        ),
        migrations.AddField(
            model_name='customerdirectory',
            name='masq_caller_id',
            field=models.BooleanField(default=False, verbose_name='Masq callerID'),
        ),
        migrations.AddField(
            model_name='customerdirectory',
            name='urgency_numbr',
            field=models.BooleanField(default=True, help_text='You have also to allow global routing option\n          and define an urgency ratecard', verbose_name='Allow urgency numbers'),
        ),
    ]
