# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-08 17:34
from __future__ import unicode_literals

from django.db import migrations
import migrate_sql.operations


class Migration(migrations.Migration):

    dependencies = [
        ('customerdirectory', '0007_auto_20161129_0913'),
    ]

    operations = [
        migrate_sql.operations.CreateSQL(
            name=b'subscriber_view',
            sql=b'DROP VIEW IF EXISTS subscriber CASCADE; CREATE OR REPLACE VIEW subscriber AS  SELECT row_number() OVER () AS id,  c.name AS username,  ud.domain,  c.password FROM customer_directory c LEFT JOIN uid_domain ud  ON c.domain_id = ud.id WHERE c.enabled=True and c.registration=True;',
            reverse_sql=b'DROP subscriber',
        ),
    ]
