# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 18:31
from __future__ import unicode_literals

from django.db import migrations
import migrate_sql.operations


class Migration(migrations.Migration):

    dependencies = [
        ('customerdirectory', '0008_auto_20161208_1834'),
    ]

    operations = [
        migrate_sql.operations.CreateSQL(
            name=b'address_view',
            sql=b'DROP VIEW IF EXISTS address CASCADE; CREATE OR REPLACE VIEW address AS  SELECT row_number() OVER () AS id,  1 AS grp,  CAST(LEFT(CAST(c.sip_ip AS VARCHAR), LENGTH(CAST(c.sip_ip AS VARCHAR)) - 3) AS VARCHAR) AS ip_addr,  CAST(RIGHT(CAST(c.sip_ip AS VARCHAR), 2) AS INTEGER) AS mask,  CAST(c.sip_port AS INTEGER) AS port,  CAST(c.name AS VARCHAR) AS tag FROM customer_directory c WHERE c.enabled=True and c.registration=False UNION ALL SELECT row_number() OVER () AS id,  10 AS grp,  CAST(sg.proxy AS VARCHAR) AS ip_addr,  32 AS mask,  5060 AS port,  sg.name AS tag FROM sofia_gateway sg WHERE sg.enabled=True and sg.register=False;',
            reverse_sql=b'DROP address',
        ),
    ]
