# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 15:32
from __future__ import unicode_literals

from django.db import migrations
import migrate_sql.operations


class Migration(migrations.Migration):

    dependencies = [
        ('customerdirectory', '0017_auto_20180207_1116'),
    ]

    operations = [
        migrate_sql.operations.ReverseAlterSQL(
            name=b'address_view',
            sql=b'DROP VIEW IF EXISTS address CASCADE ',
            reverse_sql=b'DROP VIEW IF EXISTS address CASCADE; CREATE OR REPLACE VIEW address AS SELECT row_number() OVER () AS id, * FROM (  SELECT  1 AS grp,  CAST(LEFT(CAST(c.sip_ip AS VARCHAR), LENGTH(CAST(c.sip_ip AS VARCHAR)) - 3) AS VARCHAR) AS ip_addr,  CAST(RIGHT(CAST(c.sip_ip AS VARCHAR), 2) AS INTEGER) AS mask,  CAST(c.sip_port AS INTEGER) AS port,  CAST(c.name AS VARCHAR) AS tag FROM customer_directory c WHERE c.enabled=True and c.registration=False UNION ALL SELECT  10 AS grp,  CAST(sg.proxy AS VARCHAR) AS ip_addr,  32 AS mask,  5060 AS port,  sg.name AS tag FROM sofia_gateway sg WHERE sg.enabled=True and sg.register=False) v;',
        ),
        migrate_sql.operations.AlterSQL(
            name=b'address_view',
            sql=b'DROP VIEW IF EXISTS address CASCADE; CREATE OR REPLACE VIEW address AS SELECT row_number() OVER () AS id, * FROM (  SELECT  1 AS grp,  CAST(LEFT(CAST(c.sip_ip AS VARCHAR), LENGTH(CAST(c.sip_ip AS VARCHAR)) - 3) AS VARCHAR) AS ip_addr,  CAST(RIGHT(CAST(c.sip_ip AS VARCHAR), 2) AS INTEGER) AS mask,  CAST(c.sip_port AS INTEGER) AS port,  CAST(c.name AS VARCHAR) AS tag FROM customer_directory c WHERE c.enabled=True and c.registration=False UNION ALL SELECT  10 AS grp,  CAST(sg.proxy AS VARCHAR) AS ip_addr,  32 AS mask,  CAST(sg.sip_port AS INTEGER) AS port,  sg.name AS tag FROM sofia_gateway sg WHERE sg.enabled=True and sg.register=False) v;',
            reverse_sql=b'DROP VIEW IF EXISTS address CASCADE ',
        ),
    ]
