# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerdirectory', '0016_auto_20170522_1123'),
        ('pyfreebill', '0017_sofiagateway_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fraud', models.BooleanField(default=False, help_text='If checked, this account will be protected by threshold fraud system by checking daily consumption.', verbose_name='Activate amount fraud system')),
                ('amount_limit_alert', models.DecimalField(decimal_places=4, default=0, help_text='Daily consumption allowed before alerting.', max_digits=12, verbose_name='Amount - alert')),
                ('amount_block_alert', models.DecimalField(decimal_places=4, default=b'10', help_text='Daily consumption allowed before blocking.', max_digits=12, verbose_name='Amount - block')),
                ('high_amount_alert_sent', models.BooleanField(default=False, verbose_name='Fraud alert ON (based on daily consumption)')),
                ('minutes_fraud', models.BooleanField(default=False, help_text='If checked, this account will be protected by threshold fraud system by checking daily minutes consumption.', verbose_name='Activate minutes fraud system')),
                ('minutes_limit_alert', models.IntegerField(default=0, help_text='Daily minutes consumption allowed before alerting.', verbose_name='Nb minutes - alert')),
                ('minutes_block_alert', models.IntegerField(default=b'10', help_text='Daily minutes consumption allowed before blocking.', verbose_name='Nb minutes - Block')),
                ('high_minutes_alert_sent', models.BooleanField(default=False, verbose_name='Fraud alert ON (based on daily minutes consumption)')),
                ('account_blocked_alert_sent', models.BooleanField(default=False, verbose_name='Account blocked - Fraud alert ON')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyfreebill.Company')),
                ('customerdirectory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerdirectory.CustomerDirectory')),
            ],
            options={
                'db_table': 'fraud_alert',
                'verbose_name': 'antifraud',
                'verbose_name_plural': 'antifraud',
            },
        ),
    ]
