# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifraud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraud',
            name='amount_block_alert',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Daily consumption allowed before blocking.', max_digits=12, verbose_name='Amount - block'),
        ),
        migrations.AlterField(
            model_name='fraud',
            name='minutes_block_alert',
            field=models.IntegerField(default=0, help_text='Daily minutes consumption allowed before blocking.', verbose_name='Nb minutes - Block'),
        ),
    ]
