# Generated by Django 2.1.4 on 2018-12-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_did', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'customer_enabled': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='didcustomer', to='pyfb_company.Customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='did',
            name='description',
            field=models.TextField(blank=True, max_length=30, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='did',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'supplier_enabled': True}, on_delete=django.db.models.deletion.CASCADE, related_name='didprovider', to='pyfb_company.Provider', verbose_name='Provider'),
        ),
    ]
