# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyfreebill', '0003_auto_20161025_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ip', models.CharField(help_text='Customer IP address.', max_length=100, null=True, verbose_name='customer IP address')),
                ('uuid', models.CharField(max_length=100, null=True, verbose_name='UUID')),
                ('bleg_uuid', models.CharField(default=b'', max_length=100, null=True, verbose_name='b leg UUID')),
                ('caller_id_number', models.CharField(max_length=100, null=True, verbose_name='caller ID num')),
                ('destination_number', models.CharField(max_length=100, null=True, verbose_name='Dest. number')),
                ('chan_name', models.CharField(max_length=100, null=True, verbose_name='channel name')),
                ('start_stamp', models.DateTimeField(db_index=True, null=True, verbose_name='start time')),
                ('answered_stamp', models.DateTimeField(null=True, verbose_name='answered time')),
                ('end_stamp', models.DateTimeField(null=True, verbose_name='hangup time')),
                ('duration', models.IntegerField(null=True, verbose_name='global duration')),
                ('effectiv_duration', models.IntegerField(help_text='Global call duration since call has been received by the switch in ms.', null=True, verbose_name='total duration')),
                ('effective_duration', models.IntegerField(help_text='real call duration in s.', null=True, verbose_name='effective duration')),
                ('billsec', models.IntegerField(help_text='billed call duration in s.', null=True, verbose_name='billed duration')),
                ('read_codec', models.CharField(max_length=20, null=True, verbose_name='read codec')),
                ('write_codec', models.CharField(max_length=20, null=True, verbose_name='write codec')),
                ('hangup_cause', models.CharField(db_index=True, max_length=50, null=True, verbose_name='hangup cause')),
                ('hangup_cause_q850', models.IntegerField(null=True, verbose_name='q.850')),
                ('cost_rate', models.DecimalField(decimal_places=5, default=b'0', max_digits=11, null=True, verbose_name='buy rate')),
                ('total_sell', models.DecimalField(decimal_places=5, default=b'0', max_digits=11, null=True, verbose_name='total sell')),
                ('total_cost', models.DecimalField(decimal_places=5, default=b'0', max_digits=11, null=True, verbose_name='total cost')),
                ('prefix', models.CharField(max_length=30, null=True, verbose_name='Prefix')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('rate', models.DecimalField(decimal_places=5, max_digits=11, null=True, verbose_name='sell rate')),
                ('init_block', models.DecimalField(decimal_places=5, max_digits=11, null=True, verbose_name='Connection fee')),
                ('block_min_duration', models.IntegerField(null=True, verbose_name='increment')),
                ('sip_user_agent', models.CharField(max_length=100, null=True, verbose_name='sip user agent')),
                ('sip_rtp_rxstat', models.CharField(max_length=30, null=True, verbose_name='sip rtp rx stat')),
                ('sip_rtp_txstat', models.CharField(max_length=30, null=True, verbose_name='sip rtp tx stat')),
                ('switchname', models.CharField(default=b'', max_length=100, null=True, verbose_name='switchname')),
                ('switch_ipv4', models.CharField(default=b'', max_length=100, null=True, verbose_name='switch ipv4')),
                ('hangup_disposition', models.CharField(default=b'', max_length=100, null=True, verbose_name='hangup disposition')),
                ('sip_hangup_cause', models.CharField(default=b'', max_length=100, null=True, verbose_name='SIP hangup cause')),
                ('sell_destination', models.CharField(blank=True, db_index=True, default=b'', max_length=128, null=True, verbose_name='sell destination')),
                ('cost_destination', models.CharField(blank=True, db_index=True, default=b'', max_length=128, null=True, verbose_name='cost destination')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_related', to='pyfreebill.Company', verbose_name='customer')),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyfreebill.SofiaGateway', verbose_name='gateway')),
                ('lcr_carrier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_related', to='pyfreebill.Company', verbose_name='provider')),
                ('lcr_group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyfreebill.LCRGroup', verbose_name='lcr group')),
                ('ratecard_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyfreebill.RateCard', verbose_name='ratecard')),
            ],
            options={
                'ordering': ('start_stamp', 'customer'),
                'db_table': 'cdr',
                'verbose_name': 'CDR',
                'verbose_name_plural': 'CDRs',
            },
        ),
    ]
