# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='hangup_disposition',
            field=models.CharField(default=b'', help_text='Interpretation of these values differs on incoming and\n            outgoing calls since FreeSWITCH is at different ends of the\n            session.\n\n            <b>Incoming :</b>\n            send_bye    FS sent BYE to the caller (we hung up)\n            recv_bye    FS received BYE from the caller (they hung up)\n            send_refuse FS rejected the call (e.g. 4xx or 5xx)\n            send_cancel n/a\n\n            <b>Outgoing :</b>\n            send_bye    FS sent BYE to the endpoint (we hung up)\n            recv_bye    FS received BYE from the endpoint (they hung up)\n            send_refuse Endpoint rejected the call (e.g. 4xx or 5xx)\n            send_cancel FS aborted the call (we sent CANCEL)', max_length=100, null=True, verbose_name='hangup disposition'),
        ),
    ]
