# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerdirectory', '0007_auto_20161129_0913'),
        ('cdr', '0002_auto_20161116_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='customerdirectory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customerdirectory.CustomerDirectory', verbose_name='sip account'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='insee_code',
            field=models.PositiveIntegerField(blank=True, help_text='Postal code, INSEE code ... for routing\n          urgency number to the right urgency call center.', null=True, verbose_name='Special code for routing urgency numbers'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='kam_uuid',
            field=models.CharField(max_length=100, null=True, verbose_name='SIP Server unique call-ID'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='rctype',
            field=models.CharField(blank=True, help_text='Type of calls.', max_length=10, null=True, verbose_name='Type of call'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='sipserver_name',
            field=models.CharField(default=b'', max_length=100, null=True, verbose_name='FSIP server name'),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='switchname',
            field=models.CharField(default=b'', max_length=100, null=True, verbose_name='Media server name'),
        ),
    ]
