# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0004_auto_20170522_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdr',
            name='customerdirectory_id',
        ),
    ]
