# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0005_remove_cdr_customerdirectory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='customerdirectory_id',
            field=models.CharField(max_length=50, null=True, verbose_name='sip account'),
        ),
        migrations.AddIndex(
            model_name='cdr',
            index=models.Index(fields=[b'customerdirectory_id'], name='cdr_custome_b16206_idx'),
        ),
    ]
