# Generated by Django 2.1.9 on 2019-06-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_reporting', '0002_auto_20190521_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='duration',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True, verbose_name='global duration'),
        ),
    ]
