# Generated by Django 2.1.9 on 2019-06-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_reporting', '0003_auto_20190618_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdr',
            old_name='callee_destintaion',
            new_name='callee_destination',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='billsec',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='block_min_duration',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='effectiv_duration',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='effective_duration',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='init_block',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='sip_hangup_cause',
        ),
        migrations.AlterField(
            model_name='cdr',
            name='duration',
            field=models.DecimalField(decimal_places=3, help_text='billed call duration in s.', max_digits=13, null=True, verbose_name='global duration'),
        ),
    ]
