# Generated by Django 2.1.9 on 2019-06-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_reporting', '0004_auto_20190621_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdr',
            name='chan_name',
        ),
    ]
