# Generated by Django 2.1.8 on 2020-05-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_reporting', '0007_auto_20200219_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdr',
            options={'ordering': ('-start_time',), 'verbose_name': 'cdr', 'verbose_name_plural': 'cdrs'},
        ),
        migrations.RenameField(
            model_name='cdr',
            old_name='answered_stamp',
            new_name='answered_time',
        ),
        migrations.RenameField(
            model_name='cdr',
            old_name='end_stamp',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='cdr',
            old_name='lcr_carrier_id',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='cdr',
            old_name='start_stamp',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='bleg_uuid',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='customer_endpoint',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='lcr_group_id',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='provider_endpoint',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='ratecard_id',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='rtp_uuid',
        ),
        migrations.AddField(
            model_name='cdr',
            name='call_class',
            field=models.CharField(blank=True, help_text='Class of calls.', max_length=10, null=True, verbose_name='Class of call'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='rated',
            field=models.DateTimeField(null=True, verbose_name='time cdr was rated'),
        ),
    ]
