# Generated by Django 2.1.8 on 2020-05-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_kamailio', '0015_acccdr_cdr_id'),
        ('pyfb_reporting', '0008_auto_20200520_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='cdr_acc',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accs', to='pyfb_kamailio.Acc', verbose_name='Gross CDR'),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='media_server',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdrs', to='pyfb_kamailio.RtpEngine', verbose_name='Media server name'),
        ),
    ]
