# Generated by Django 2.1.8 on 2020-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_reporting', '0009_auto_20200526_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='billsec',
            field=models.DecimalField(decimal_places=3, help_text='billed call duration in s.', max_digits=13, null=True, verbose_name='global duration'),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='duration',
            field=models.DecimalField(decimal_places=3, help_text='effective call duration in s.', max_digits=13, null=True, verbose_name='call duration'),
        ),
    ]
