# Generated by Django 2.1.8 on 2020-05-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_kamailio', '0015_acccdr_cdr_id'),
        ('pyfb_reporting', '0011_auto_20200529_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='billsec',
            field=models.IntegerField(default=0, help_text='billed call duration in s.', verbose_name='billed duration'),
        ),
        migrations.AddField(
            model_name='cdr',
            name='cdr_acc',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accs', to='pyfb_kamailio.AccCdr', verbose_name='Gross CDR'),
        ),
    ]
