# Generated by Django 2.1.8 on 2020-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_reporting', '0013_auto_20200529_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='costsec',
            field=models.IntegerField(default=0, help_text='billed call duration in sec by provider', verbose_name='provider billed duration'),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='billsec',
            field=models.IntegerField(default=0, help_text='billed call duration in sec for customer', verbose_name='customer billed duration'),
        ),
    ]
