# Generated by Django 2.2.17 on 2021-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_reporting', '0014_auto_20200610_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='sip_rtp_rxstat',
            field=models.CharField(default='', max_length=30, verbose_name='MOS Rx'),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='sip_rtp_txstat',
            field=models.CharField(default='', max_length=30, verbose_name='MOS Tx'),
        ),
    ]
