# Generated by Django 2.1.4 on 2018-12-21 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_company', '0004_auto_20181210_1138'),
        ('pyfb_routing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRoutingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(blank=True, max_length=30, verbose_name='Comment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfb_company.Customer', verbose_name='customer')),
                ('routinggroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfb_routing.RoutingGroup', verbose_name='routing group')),
            ],
            options={
                'verbose_name_plural': 'Customer routing group Allocations',
                'verbose_name': 'Customer Routing group Allocation',
                'db_table': 'pyfb_routing_c_routinggrp',
                'ordering': ('customer', 'routinggroup'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='customerroutinggroup',
            unique_together={('customer', 'routinggroup')},
        ),
    ]
