# Generated by Django 2.1.5 on 2020-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_kamailio', '0011_auto_20200514_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='call_direction',
            field=models.CharField(default='', help_text='inbound / outbound', max_length=128),
        ),
        migrations.AddField(
            model_name='acc',
            name='called_destination',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='called_did',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='acc',
            name='caller_destination',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='did_destination',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='e164_called',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='acc',
            name='e164_caller',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='acc',
            name='leg_a_class',
            field=models.CharField(default='', help_text='on-net / off-net', max_length=128),
        ),
        migrations.AddField(
            model_name='acc',
            name='leg_b_class',
            field=models.CharField(default='', help_text='on-net / off-net', max_length=128),
        ),
        migrations.AddField(
            model_name='acc',
            name='o_c_rate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='o_c_rate_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='o_p_rate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='o_p_rate_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='orig_customer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='orig_provider',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='t_c_rate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='t_c_rate_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='t_p_rate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='t_p_rate_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='term_customer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acc',
            name='term_provider',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
