# Generated by Django 2.1.5 on 2020-05-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_kamailio', '0015_acccdr_cdr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acccdr',
            name='cdr_id',
        ),
        migrations.AddField(
            model_name='acccdr',
            name='processed',
            field=models.DateTimeField(null=True, verbose_name='time cdr was processed'),
        ),
    ]
