# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='carrier name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-name',),
                'db_table': 'dest_carrier',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_iso2', django_countries.fields.CountryField(max_length=2, unique=True, verbose_name='country')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nb_destination', models.IntegerField(default=0, verbose_name='NB of associated destinations')),
            ],
            options={
                'ordering': ('-country_iso2',),
                'db_table': 'dest_country',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name of destination')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('country_iso2', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country')),
                ('nb_prefix', models.IntegerField(default=0, verbose_name='Nb of associated prefix')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='direction.Carrier', verbose_name='carrier')),
            ],
            options={
                'ordering': ('-name',),
                'db_table': 'dest_destination',
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='International public telecommunication prefix (maximum 15 digits)', max_length=15, unique=True, verbose_name='prefix')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='direction.Destination', verbose_name='destination')),
            ],
            options={
                'ordering': ('-prefix',),
                'db_table': 'dest_prefix',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='region name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nb_country', models.IntegerField(default=0, verbose_name='NB of associated countries')),
            ],
            options={
                'ordering': ('-name',),
                'db_table': 'dest_region',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='type of destination')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-name',),
                'db_table': 'dest_type',
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='direction.Type', verbose_name='Type of destination'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.Region', verbose_name='region'),
        ),
    ]
