# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('country_iso2',)},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='prefix',
            options={'ordering': ('prefix',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='country',
            name='nb_destination',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='nb_prefix',
        ),
        migrations.RemoveField(
            model_name='region',
            name='nb_country',
        ),
    ]
