# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyfreebill', '0003_auto_20161025_1701'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_directory',
            table='customer_directory-old',
        ),
    ]
