# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('did', '0004_auto_20161029_1134'),
        ('pyfreebill', '0004_auto_20161029_1103'),
    ]

    # This needs to be a state-only operation because the database model was
    # renamed, and no longer exists according to Django.
    state_operations = [
        # Pasted from auto-generated operations in previous step:
        migrations.DeleteModel(
            name='CustomerDirectory',
        ),
    ]

    operations = [
        # After this state operation, the Django DB state should match the
        # actual database structure.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
