# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('did', '0004_auto_20161029_1134'),
        ('pyfreebill', '0004_auto_20161029_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdirectory',
            name='company',
        ),
        migrations.DeleteModel(
            name='CustomerDirectory',
        ),
    ]
