# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0002_domain'),
        ('pyfreebill', '0005_auto_20161029_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofiagateway',
            name='domain',
            field=models.ForeignKey(default=1, help_text='A gateway must belong to a domain.\n            This domain must be used in SIP message', on_delete=django.db.models.deletion.CASCADE, to='switch.Domain', verbose_name='SIP domain'),
            preserve_default=False,
        ),
    ]
