# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfreebill', '0006_sofiagateway_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='rctype',
            field=models.CharField(choices=[(b'PSTN', 'CALLS TO PSTN'), (b'DIDIN', 'DID - INBOUND CALLS'), (b'DIDOUT', 'OUTBOUND CALLS TO INTERNAL DID'), (b'EMERGENCY', 'EMERGENCY CALLS')], default=b'PSTN', help_text='Select the right ratecard\n            regarding the type of calls. Default is PSTN', max_length=10, verbose_name='Type of ratecards'),
        ),
    ]
