# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfreebill', '0007_ratecard_rctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrates',
            name='destination',
            field=models.TextField(blank=True, db_index=True, default=b'', max_length=30, null=True, verbose_name='destination'),
        ),
    ]
