# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfreebill', '0008_auto_20161117_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrates',
            name='destination',
            field=models.CharField(blank=True, db_index=True, default=b'', max_length=128, null=True, verbose_name='destination'),
        ),
    ]
