# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfreebill', '0011_auto_20161117_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerratecards',
            name='description',
            field=models.CharField(blank=True, max_length=30, verbose_name='Comment'),
        ),
    ]
