# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfreebill', '0012_auto_20161118_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipprofile',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
