# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfreebill', '0013_sipprofile_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrates',
            name='minimal_time',
            field=models.IntegerField(default=0, help_text='minimal time to be billed in seconds', verbose_name='Minimal time'),
        ),
    ]
