# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfreebill', '0020_auto_20180406_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sofiagateway',
            name='sip_profile',
        ),
        migrations.AddField(
            model_name='sofiagateway',
            name='sip_port',
            field=models.PositiveIntegerField(default=b'5060', help_text='Gateway SIP port (Default 5060).', verbose_name='SIP port'),
        ),
        migrations.AlterField(
            model_name='sofiagateway',
            name='sip_cid_type',
            field=models.CharField(choices=[(b'none', 'none'), (b'default', 'default'), (b'pid', 'pid'), (b'rpid', 'P-Asserted-Identity')], default=b'rpid', help_text='Modify callerID in SIP\n                                        Headers.', max_length=10, verbose_name='SIP CID type'),
        ),
    ]
