# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('did', '0002_auto_20161012_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='did',
            name='cust_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='did.CustomerRatesDid', verbose_name='customer rate plan'),
        ),
        migrations.AlterField(
            model_name='did',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='didcustomer', to='pyfreebill.Company', verbose_name='Customer'),
        ),
    ]
