# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('did', '0003_auto_20161025_1658'),
        ('customerdirectory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesdid',
            name='trunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerdirectory.CustomerDirectory'),
        ),
    ]
