# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyfreebill', '0012_auto_20161118_1758'),
        ('did', '0005_auto_20161129_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='did',
            name='cust_ratecard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyfreebill.RateCard', verbose_name='Customer rate plan'),
        ),
        migrations.AddField(
            model_name='did',
            name='prov_ratecard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyfreebill.ProviderTariff', verbose_name='provider rate plan'),
        ),
    ]
