# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('did', '0006_auto_20161129_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='did',
            name='cust_plan',
        ),
        migrations.RemoveField(
            model_name='did',
            name='prov_plan',
        ),
    ]
