# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-16 09:20
from __future__ import unicode_literals

from django.db import migrations
import migrate_sql.operations


class Migration(migrations.Migration):

    dependencies = [
        ('did', '0007_auto_20161129_0940'),
    ]

    operations = [
        migrate_sql.operations.CreateSQL(
            name=b'dbaliases_view',
            sql=b"DROP VIEW IF EXISTS dbaliases CASCADE; CREATE OR REPLACE VIEW dbaliases AS  SELECT row_number() OVER () AS id,  d.number AS alias_username,  '' AS alias_domain,  cd.name AS username,  ud.domain FROM did_routes dr LEFT JOIN did d  ON dr.contract_did_id = d.id AND dr.type = 's' LEFT JOIN customer_directory cd  ON dr.trunk_id = cd.id LEFT JOIN uid_domain ud  ON ud.id = cd.domain_id;",
            reverse_sql=b'DROP dbaliases',
        ),
    ]
