#!/usr/bin/env bash

# PKS P-KISS-SBC
# (c) 2022 Mathias WOLFF
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

VERSION="1.0.0"
APP_NAME="PKS"
SCRIPT_NAME=$(basename "$0")
ENV_FILE="/srv/.env"
DC_FILE="/usr/src/pyfreebilling/src/sip/docker-compose.yml"
DOCKER_COMPOSE=(docker compose -f ${DC_FILE} --env-file ${ENV_FILE})

colorFunc(){
  COL_BOLD=$'\e[0;1m'
  COL_ULINE=$'\e[0;4m'
  COL_NC=$'\e[0;0m'
  COL_GRAY=$'\e[0;90m'
  COL_RED=$'\e[0;91m'
  COL_GREEN=$'\e[0;92m'
  COL_YELLOW=$'\e[0;93m'
  COL_BLUE=$'\e[0;94m'
  COL_PURPLE=$'\e[0;95m'
  COL_CYAN=$'\e[0;96'

  TICK="[${COL_GREEN}✓${COL_NC}]"
  CROSS="[${COL_RED}✗${COL_NC}]"
  INFO="[i]"
  QST="[?]"
  DONE="${COL_GREEN} done!${COL_NC}"
  OVER="\\r[K"
}

test_prerequesites(){
  echo "test if prerequesites are respected"
}

install_prerequesites(){
  echo "Install prerequesites"
}

Select_db(){
    echo "Before installation, where do you want to store data ?"
    PS3="Select your DB choice please: "

    select db in Default DBtext MySQL PostgreSQL SQLite Quit
    do
        case $db in
            "Default")
                echo "$db database selected - we will use DBText";;
            "MySQL")
                echo "$db database selected";;
            "PostgreSQL")
                echo "$db database selected";;
            "SQLite")
                echo "$db database selected";;
            "Quit")
                echo "Install process aborted"
                break;;
            *)
                echo "Ooops - unknown choice";;
        esac
    done
}

startFunc(){
  echo -e "  ${INFO} Start PKS ..."
  "${DOCKER_COMPOSE[@]}" up -d
  exit 1
}

stopFunc(){
  echo -e "  ${INFO} Stop PKS ..."
  "${DOCKER_COMPOSE[@]}" down
  exit 1
}

restartFunc(){
    echo -e "  ${INFO} Stop PKS ..."
  "${DOCKER_COMPOSE[@]}" down
  sleep 1
  echo -e "  ${INFO} Start PKS ..."
  "${DOCKER_COMPOSE[@]}" up -d
  exit 1
}

reloadFunc(){
  echo "PKS will reload data from database"
  echo "  ${INFO} Reload address table ..."
  docker exec -t pks-sip kamcmd permissions.addressReload
  sleep 1
  echo "  ${INFO} Reload dialplan table ..."
  docker exec -t pks-sip kamcmd dialplan.reload
  sleep 1
  echo "  ${INFO} Reload tenant table ..."
  docker exec -t pks-sip kamcmd htable.reload tenantmap
  sleep 1
  echo "  ${INFO} Reload dispatcher table ..."
  docker exec -t pks-sip kamcmd dispatcher.reload
  echo "  ${INFO} PKS has been refreshed with latest data"
}

debugFunc(){
  "${DOCKER_COMPOSE[@]}" logs --tail=100 -f
  exit 1
}

statusFunc(){
  "${DOCKER_COMPOSE[@]}" ps
  exit 1
}

dbFunc(){
  # Menu
  PS3="Select the table to view please: "

  select db in Dispatcher Tenant Dialplan Address Quit
  do
    case $db in
      "Dispatcher")
          echo "  ${INFO}Content of $db :"
          docker exec -t pks-sip kamcmd dispatcher.list | less;;
      "Tenant")
          echo "  ${INFO}Content of $db :"
          docker exec -t pks-sip kamcmd htable.dump tenantmap | less;;
      "Dialplan")
          read -rp "  ${QST} Do you want to see DID or external routes [dD/eE] : " answer
            case ${answer} in
              [Dd]* ) echo "  ${INFO}Content of DID $db :"
                      docker exec -t pks-sip kamcmd dialplan.dump 1;;
              [Ee]* ) echo "  ${INFO}Content of DID $db :"
                      docker exec -t pks-sip kamcmd dialplan.dump 2;;
              * ) echo -e "${OVER}  ${COL_YELLOW}Ooops - unknown choice${COL_NC}";;
            esac;;
      "Address")
          echo "  ${INFO}Content of $db :"
          docker exec -t pks-sip kamcmd permissions.addressDump | less;;
      "Quit")
          echo "  ${INFO}We're done"
          break;;
      *)
          echo "Ooops - unknown choice";;
    esac
  done
}

helpFunc(){
  echo "Usage: pks [options]
  Example: 'pks -r -h'
  Add '-h' after specific commands for more information on usage

  Admin Options:
    start              start PKS
    stop               stop PKS
    restart            restart PKS
    -r, reload         reload PKS

  Debugging Options:
    -d, debug          View the live output of the PKS log
    -s, status         PKS containers status
    db                 Database internal data

  Options:
    -h, --help, help   Show this help dialog  
    -v, version        Show installed version
    uninstall          Uninstall PKS from your system
    update             Update PKS

  install              Install PKS
  ";

  exit 0
}

versionFunc(){
  echo -e "PKS version ${VERSION}"
  exit 0
}

uninstallFunc(){
  echo "Not available, sorry"
  exit 0
}

updateFunc(){
  read -rp "  ${QST} PKS will be updated. ${COL_BOLD}${COL_RED}PKS will be retarded${COL_NC}, are you sure ? [y/N]" answer
  case ${answer} in
    [Yy]* ) echo -e "  ${INFO} Starting update ...";;
    * ) echo -e "${OVER}  ${COL_GREEN}Update has been canceled${COL_NC}"; exit 0;;
  esac
  
  "${DOCKER_COMPOSE[@]}" build
  echo -e "  ${TICK} Update successfully ${DONE}"
  restartFunc
  exit 0
}

installFunc(){
  echo "Not available, sorry"
  exit 0
}

###### MAIN #####

colorFunc

if [[ $# = 0 ]]; then
  helpFunc
fi

case "${1}" in
  "start"                       ) startFunc "$@";;
  "stop"                        ) stopFunc "$@";;
  "restart"                     ) restartFunc "$@";;
  "-r" | "reload"               ) reloadFunc "$@";;
  "-d" | "debug"                ) debugFunc "$@";;
  "-s" | "status"               ) statusFunc "$@";;
  "db"                          ) dbFunc "$@";;
  "-h" | "help" | "--help"      ) helpFunc;;
  "-v" | "version"              ) versionFunc "$@";;
  "uninstall"                   ) uninstallFunc "$@";;
  "update"                      ) updateFunc "$@";;
  "install"                     ) installFunc "$@";;
  *                             ) helpFunc;;
esac
