# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='rule title')),
                ('match_op', models.IntegerField(choices=[(0, 'Equal'), (1, 'Regex')], default=0, verbose_name='Type of match (equal or regex)')),
                ('match_exp', models.CharField(blank=True, default=b'', max_length=64, verbose_name='match expression')),
                ('match_len', models.IntegerField(default=1, verbose_name='match length')),
                ('subst_exp', models.CharField(blank=True, default=b'', max_length=64, verbose_name='subst prefix')),
                ('repl_exp', models.CharField(blank=True, default=b'', max_length=64, verbose_name='replacement prefix')),
                ('attrs', models.CharField(blank=True, default=b'', max_length=64, verbose_name='attributes')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
            options={
                'ordering': ('name', 'match_exp'),
                'db_table': 'normalization_rule',
                'verbose_name': 'Normalization Rule',
                'verbose_name_plural': 'Normalization Rules',
            },
        ),
    ]
