# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-16 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalizationrule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizationrule',
            name='attrs',
            field=models.CharField(blank=True, choices=[(b'', 'N/A')], default=b'', help_text='Rule to map specific route -\n            Default set to nothing : N/A - not used', max_length=64, verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='normalizationrule',
            name='match_exp',
            field=models.CharField(blank=True, default=b'', help_text='Example : ^(33)[0-9].*', max_length=64, verbose_name='match expression'),
        ),
        migrations.AlterField(
            model_name='normalizationrule',
            name='match_op',
            field=models.IntegerField(choices=[(0, 'Equal'), (1, 'Regex')], default=1, verbose_name='Type of match (equal or regex)'),
        ),
        migrations.AlterField(
            model_name='normalizationrule',
            name='repl_exp',
            field=models.CharField(blank=True, default=b'', help_text='Example : 0033\x01', max_length=64, verbose_name='replacement prefix'),
        ),
        migrations.AlterField(
            model_name='normalizationrule',
            name='subst_exp',
            field=models.CharField(blank=True, default=b'', help_text='Example : ^(33)([0-9].*)', max_length=64, verbose_name='subst prefix'),
        ),
    ]
