# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-16 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizationrule', '0002_auto_20161116_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallMappingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='rule title')),
                ('dpid', models.IntegerField(default=0, help_text='Need to be 0, instead of the rule\n            will not be used', verbose_name='Dialplan id')),
                ('pr', models.IntegerField(help_text='Priority of rule', unique=True, verbose_name='Priority rule')),
                ('match_op', models.IntegerField(choices=[(0, 'Equal'), (1, 'Regex')], default=1, verbose_name='Type of match (equal or regex)')),
                ('match_exp', models.CharField(blank=True, default=b'', help_text='Example : ^(33)[0-9].*', max_length=64, verbose_name='match expression')),
                ('match_len', models.IntegerField(default=1, verbose_name='match length')),
                ('subst_exp', models.CharField(blank=True, default=b'', help_text='Example : ^(33)([0-9].*)', max_length=64, verbose_name='subst prefix')),
                ('repl_exp', models.CharField(blank=True, default=b'', help_text='Example : 0033\x01', max_length=64, verbose_name='replacement prefix')),
                ('attrs', models.CharField(blank=True, choices=[(b'', 'N/A'), (b'PSTN', 'PSTN'), (b'EMERGENCY', 'EMERGENCY NUMBER'), (b'OWN', 'OWN NUMBERS'), (b'SPEEDDIAL', 'SPEED DIAL'), (b'DROP', 'DROP NUMBERS')], default=b'', help_text='Rule to map specific route -\n            Default set to nothing : N/A', max_length=64, verbose_name='attributes')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
            options={
                'ordering': ('pr',),
                'db_table': 'call_mapping_rule',
                'verbose_name': 'Call Mapping Rule',
                'verbose_name_plural': 'Call Mapping Rules',
            },
        ),
        migrations.CreateModel(
            name='NormalizationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Rule Group name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'normalization_grp',
                'verbose_name': 'Normalization Group',
                'verbose_name_plural': 'Normalization Groups',
            },
        ),
        migrations.CreateModel(
            name='NormalizationRuleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr', models.IntegerField(help_text='Rule order', verbose_name='priority')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('dpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalizationrule.NormalizationGroup', verbose_name='Normalization Group')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalizationrule.NormalizationRule', verbose_name='Normalization Rule')),
            ],
            options={
                'ordering': ('dpid', 'pr', 'rule'),
                'db_table': 'normalization_rule_grp',
                'verbose_name': 'Normalization Rule-Group',
                'verbose_name_plural': 'Normalization Rules-Groups',
            },
        ),
        migrations.AlterUniqueTogether(
            name='callmappingrule',
            unique_together=set([('dpid', 'pr')]),
        ),
        migrations.AlterUniqueTogether(
            name='normalizationrulegroup',
            unique_together=set([('dpid', 'pr')]),
        ),
    ]
