# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalizationrule', '0003_auto_20161116_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normalizationrulegroup',
            options={'ordering': ('dpid', 'pr'), 'verbose_name': 'Normalization Rule-Group', 'verbose_name_plural': 'Normalization Rules-Groups'},
        ),
        migrations.AlterField(
            model_name='callmappingrule',
            name='match_len',
            field=models.IntegerField(default=0, verbose_name='match length'),
        ),
        migrations.AlterField(
            model_name='normalizationrule',
            name='match_len',
            field=models.IntegerField(default=0, verbose_name='match length'),
        ),
        migrations.AlterField(
            model_name='normalizationrule',
            name='repl_exp',
            field=models.CharField(blank=True, default=b'', help_text='Example : 0033\x01', max_length=64, verbose_name='replacement expression'),
        ),
        migrations.AlterField(
            model_name='normalizationrule',
            name='subst_exp',
            field=models.CharField(blank=True, default=b'', help_text='Example : ^(33)([0-9].*)', max_length=64, verbose_name='substitution expression'),
        ),
    ]
