# Generated by Django 2.1.4 on 2018-12-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_company', '0002_auto_20181210_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_balance',
        ),
        migrations.AddField(
            model_name='company',
            name='customer_balance',
            field=models.DecimalField(decimal_places=6, default=0, help_text='actual customer balance.', max_digits=12, verbose_name='customer balance'),
        ),
        migrations.AddField(
            model_name='company',
            name='provider_balance',
            field=models.DecimalField(decimal_places=6, default=0, help_text='actual provider balance.', max_digits=12, verbose_name='provider balance'),
        ),
    ]
