# Generated by Django 2.1.4 on 2020-09-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfb_company', '0005_customer_blocking_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customer_balance_update',
            field=models.BooleanField(default=True, verbose_name='provider balance is updated after each call'),
        ),
        migrations.AddField(
            model_name='company',
            name='provider_balance_update',
            field=models.BooleanField(default=False, verbose_name='provider balance is updated after each call'),
        ),
    ]
