# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipdialog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'ordering': ('-pk',), 'verbose_name': 'SIP dialog', 'verbose_name_plural': 'SIP dialogs'},
        ),
        migrations.AlterModelOptions(
            name='dialogvar',
            options={'ordering': ('-pk',), 'verbose_name': 'SIP dialog vars', 'verbose_name_plural': 'SIP dialog vars'},
        ),
    ]
