# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='version',
            table='version',
        ),
    ]
